# # -*- coding: utf-8 -*-
# """Mutation.ipynb

# Automatically generated by Colaboratory.

# Original file is located at
#     https://colab.research.google.com/drive/1lt58k3mclnI85Xwlrt4EIwEzeR4pxBtn
# """

# import json

# # Opening JSON file
# f = open('output.json')

# # returns JSON object as
# # a dictionary
# data = json.load(f)

# # Iterating through the json
# # list

# f.close()
# type(data['TABLE'])

# data

# for i in data['COLUMN']:
#     print(i)

def is_mutation_req(data):
  if (data['CRUD']=='UPDATE' or data['CRUD']=='INSERT' or data['CRUD'] == 'DELETE'):
    return True
  return False

def graphql_schema(data):
  for i in data['TABLE']:
    print("{} : \{ ".format(i))
    for j in data['COLUMN']:
      print(j)



def mutation(data):
  res = "mutation () { "
  res += "\n\t{}_mut_{} {{".format(data['CRUD'][0], data['TABLE'][0])
  res += "\n\t\taffected rows"
  res += "\n\t\treturning {"
  for i in data['COLUMN']:
    res += "\n\t\t\t{}".format(i)
  res += "\n\t\t}"
  res += "\n\t}"
  res += "\n}"
  return res

# mutation(data)